# Generated by Django 3.2.9 on 2022-01-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantie', models.IntegerField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ManyToManyField(to='produits.Produit')),
            ],
        ),
    ]
