# Generated by Django 3.2.9 on 2022-01-20 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_album', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutiue', models.CharField(max_length=30, null=True)),
                ('lieu_boutique', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boutique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cathegorie', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100, null=True)),
                ('quantité_produit', models.IntegerField(null=True)),
                ('prix_promo', models.IntegerField(blank=True, default=0)),
                ('prix_produit', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('promo', 'promo'), ('solde', 'solde'), ('nouveau', 'nouveau')], default='vendre', max_length=100)),
                ('description_du_produit', models.CharField(blank=True, default=' ', max_length=10000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produits.album')),
                ('boutique', models.ManyToManyField(to='produits.Boutique')),
                ('cathegorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_image', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.album')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
                ('adresse_email', models.EmailField(max_length=254, null=True)),
                ('avis', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
            ],
        ),
    ]
