# Generated by Django 3.2.9 on 2022-02-07 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produits.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produits', '0002_auto_20220121_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.CharField(blank=True, choices=[('promo', 'promo'), ('solde', 'solde'), ('nouveau', 'nouveau')], default='nouveau', max_length=100),
        ),
        migrations.CreateModel(
            name='Postfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=produits.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ManyToManyField(related_name='image', to='produits.Postfile'),
        ),
    ]
